# Generated by Django 4.2.7 on 2023-12-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='numeroDocumento',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
