# Generated by Django 4.2.7 on 2023-12-05 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_estudiante_activo_estudiante_numerodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='codigo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numero',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(11)]),
        ),
    ]
