# Generated by Django 4.2.7 on 2023-12-06 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_salas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='numero',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='numeroTelefono',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='promedio',
            field=models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='semestre',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='codigo',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numeroDocumento',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='salas',
            name='codigo_monitor',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='salas',
            name='edificio',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='salas',
            name='fecha',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='salas',
            name='hora',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='salas',
            name='monitor',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='salas',
            name='salas_numero',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
